#!/usr/bin/env python
#

from akramms import config,params
import argparse,itertools,os,subprocess,sys,io,codecs
from akramms import r_ramms
from akramms.util import rammsutil
from uafgi.util import ioutil

# ------------------------------------------------------------------------
# https://mike.depalatis.net/blog/simplifying-argparse.html
# https://gist.github.com/mivade/384c2c41c3a29c637cb6c603d4197f9f

cli = argparse.ArgumentParser()
subparsers = cli.add_subparsers(dest="subcommand")

def argument(*name_or_flags, **kwargs):
    """Convenience function to properly format arguments to pass to the
    subcommand decorator.
    """
    return (list(name_or_flags), kwargs)

def subcommand(args=[], parent=subparsers):
    def decorator(func):
        parser = parent.add_parser(func.__name__, description=func.__doc__)
        for arg in args:
            parser.add_argument(*arg[0], **arg[1])
        parser.set_defaults(func=func)
    return decorator
# ------------------------------------------------------------------------
# Files and folders to copy from one scene to jumpstart the next.
# TODO: Make this work for general scenes
_init_files = [
    'stats_kernel.txt',
    'crs.prj',
    'data_prep_PRA_args.pik',
    'juneau1_DataPrep_InputParameters.csv',
    'Juneau_IFSAR_DTM_AKAlbers_EPSG_3338_sinks.tif',
    'Juneau_IFSAR_DTM_AKAlbers_EPSG_3338_neighbor1.tif',
    'Juneau_IFSAR_DTM_AKAlbers_EPSG_3338_filled.tif',
    'eCog',
    r'PRA_frequent\info',
    'PRA_frequent',
    'scene.nc',
    'status.txt']

@subcommand([
    argument('dir0', help='Source run dir'),
    argument('dir1', help='Destination run dir')])
def initcopy(args):
    """Runs a single RAMMS avalanche on the local machine, via Docker"""

    dir0 = os.path.abspath(args.dir0)
    dir1 = os.path.abspath(args.dir1)
    ioutil.sync_files(dir0, _init_files, dir1)

# ------------------------------------------------------------------------

@subcommand([argument('ramms', help='RAMMS directory or release file to inspect')])
def ps(args):
    """Provides status of RAMMS avalanches"""
    release_files = rammsutil.get_release_files(args.ramms)
    #print(release_files)

    df = r_ramms.job_statuses(release_files)
    r_ramms.print_job_statuses(df)

@subcommand([
    argument('run_dir', help='Run directory to use'),
    argument('id', type=int, help='ID of avalanche in run_dir to run')])
def run(args):
    """Runs a single RAMMS avalanche on the local machine, via Docker"""

    run_dir = os.path.abspath(args.run_dir)
    parts = run_dir.split(os.sep)
    job_name = '{}_{}_{}'.format(parts[-2], parts[-1], args.id)

    r_ramms.submit_job(run_dir, job_name)

@subcommand([
    argument('ramms', help='RAMMS directory or release file to inspect'),
    argument('ids', type=int, nargs='*', help='ID of avalanche in run_dir to run')])
def submit(args):
    """Runs RAMMS for many avalanches"""

    ids = None if len(args.ids) == 0 else args.ids

    # Separate into numeric-only and non-numerica args in the spec
    release_files = rammsutil.get_release_files(args.ramms)
    r_ramms.submit_jobs(release_files, ids=ids)

@subcommand([
    argument('ramms', help='RAMMS directory or release file to inspect'),
    argument('ids', type=int, nargs='*', help='ID of avalanche in run_dir to run')])
def enlarge(args):
    """Enlarges domain of jobs that overran"""

    ids = None if len(args.ids) == 0 else args.ids

    # Separate into numeric-only and non-numerica args in the spec
    release_files = rammsutil.get_release_files(args.ramms)
    r_ramms.enlarge_domains(release_files, ids=ids)

@subcommand([
    argument('ramms', help='RAMMS directory or release file to inspect'),
    argument('ids', type=int, nargs='*', help='ID of avalanche in run_dir to inspect')])
def info(args):
    ids = None if len(args.ids) == 0 else args.ids
    release_files = rammsutil.get_release_files(args.ramms)
    infos_df = r_ramms.infos(release_files, ids=ids)


#    df = infos_df[infos_df['final_outflow_volume'] == 0.00]
    df = infos_df
#    df = df[df['final_outflow_volume'] == 0]

    print(df)

@subcommand([
    argument('ramms', help='RAMMS directory or release file to inspect'),
    argument('id', type=int, help='ID of avalanche in run_dir to inspect'),
    argument('ext', default='.out.log', help='Extension of filename to  cat')])
def cat(args):
    r_ramms.cat(args.ramms, [args.id], ext=args.ext, out_bytes=sys.stdout.buffer)

# https://stackoverflow.com/questions/51585110/how-to-encode-a-text-stream-into-a-byte-stream-in-python-3
@subcommand([
    argument('ramms', help='RAMMS directory or release file to inspect'),
    argument('id', type=int, help='ID of avalanche in run_dir to inspect'),
    argument('ext', default='.out.log', help='Extension of filename to  cat')])
def less(args):
    stdout0 = sys.stdout
    try:
        less = subprocess.Popen(['less'], stdin=subprocess.PIPE)
        
        #sys.stdout = codecs.getwriter('utf-8')(less.stdin)
        r_ramms.cat(args.ramms, [args.id], ext=args.ext, out_bytes=less.stdin)
        less.communicate()
    finally:
        sys.stdout = stdout0

@subcommand([
    argument('ramms', help='RAMMS directory or release file to inspect'),
    argument('id', type=int, help='ID of avalanche in run_dir to inspect')])
def ls(args):
    for jb,id,info in r_ramms.ls(args.ramms, [args.id]):
        sdt = '{:04d}-{:02d}-{:02d} {:02d}:{:02d}:{:02d}'.format(*info.date_time)
        print(f'{info.file_size: >11,} {sdt:19} {info.filename}')

@subcommand([
    argument('ramms', help='RAMMS directory or release file to inspect'),
])
def spec(args):
    release_files = rammsutil.get_release_files(args.ramms)
    for fname in release_files:
        print(fname)
#        print('---- tiffmap:')
#        jb = rammsutil.parse_release_file(fname)
#        map = r_ramms.tiffmap(jb)
#        for x in map:
#            print('    ',x)

@subcommand([
    argument('scene', help='Top-Level scene directory to setup through stages 0 and 1.'),
])
def setup(args):
    scene_dir = args.scene
    scene_args = params.load(scene_dir)
    print(scene_args)

    stages.run_stage0(scene_dir)
    stages.run_stage1(scene_dir)



@subcommand([
    argument('ramms', help='RAMMS directory or release file to inspect'),
])
def mosaic(args):
    release_files = rammsutil.get_release_files(args.ramms)
    for oramms_name,release_files in rammsutil.groupby_oramms(release_files):


        omap_name = os.path.join(oramms_name.scene_dir, 'maps', f'{oramms_name.ramms_name}_maps.zip')
        if os.path.exists(omap_name):
            print(f'=========== Exists, not redoing: {omap_name}')
            continue

        print(f'=========== Assembling {oramms_name.ramms_dir}')
        r_ramms.assemble_stage3(oramms_name, release_files)
        r_ramms.run_ramms_stage3(oramms_name)
#        print('orrrrrrrrr ', oramms_name.__dict__)


def rclone_relfiles(src, dest, relfiles, tdir):
    # Rclone the files
        listfile = tdir.filename(prefix='relfiles')
        with open(listfile, 'w') as out:
            for file in relfiles:
                out.write(f'{file}\n')

        # Use that in rclone command
        cmd = ['rclone', '-v', 'copy', '--files-from', listfile,
            src, dest]
        print(' '.join(cmd))
        subprocess.run(cmd, check=True)


@subcommand([
    argument('scene', help='Top-Level scene directory to setup through stages 0 and 1.'),
])
def export(args):
    scene_dir = os.path.abspath(os.path.realpath(args.scene))
    scene_args = params.load(scene_dir)

    with ioutil.TmpDir() as tdir:

        # Top-level files
        snowdepth0_leaf = os.path.split(config.roots.syspath(scene_args['snowdepth_file']))[1]
        snowdepth0_root = os.path.splitext(snowdepth0_leaf)[0]
        snowdepth_leaf = f"{snowdepth0_root}_{scene_args['name']}_select.tif"
        rclone_relfiles(
            os.path.join(config.roots.lookup['PRJ'], scene_args['name']),
            'alaska:AvalancheShare/results/{}'.format(scene_args['name']),
            ['scene.nc', 'scene.cdl', snowdepth_leaf], tdir)


        # File ins maps/ directory
        relfiles = list()
        dir = os.path.join(scene_dir, 'maps')
        for name in os.listdir(dir):
            if name.endswith('.zip'):
                relfiles.append(name)

        rclone_relfiles(
            os.path.join(config.roots.lookup['PRJ'], scene_args['name'], 'maps'),
            'alaska:AvalancheShare/results/{}'.format(scene_args['name']),
            relfiles, tdir)



def main():
    args = cli.parse_args()
    if args.subcommand is None:
        cli.print_help()
    else:
        args.func(args)

main()
