#!/usr/bin/env python
#

from akramms import config,params
import argparse,itertools,os,subprocess,sys,io,codecs,re
from akramms import r_experiment,stages,avalparse
from akramms.util import rammsutil
from uafgi.util import ioutil,make
import importlib
from akramms import r_domain_builder, r_ramms

# ------------------------------------------------------------------------
# https://mike.depalatis.net/blog/simplifying-argparse.html
# https://gist.github.com/mivade/384c2c41c3a29c637cb6c603d4197f9f

cli = argparse.ArgumentParser()
subparsers = cli.add_subparsers(dest="subcommand")

def argument(*name_or_flags, **kwargs):
    """Convenience function to properly format arguments to pass to the
    subcommand decorator.
    """
    return (list(name_or_flags), kwargs)

def subcommand(args=[], parent=subparsers):
    def decorator(func):
        parser = parent.add_parser(func.__name__, description=func.__doc__)
        for arg in args:
            parser.add_argument(*arg[0], **arg[1])
        parser.set_defaults(func=func)
    return decorator
# ------------------------------------------------------------------------
# Files and folders to copy from one scene to jumpstart the next.
# TODO: Make this work for general scenes
_init_files = [
    'stats_kernel.txt',
    'crs.prj',
    'data_prep_PRA_args.pik',
    'juneau1_DataPrep_InputParameters.csv',
    'Juneau_IFSAR_DTM_AKAlbers_EPSG_3338_sinks.tif',
    'Juneau_IFSAR_DTM_AKAlbers_EPSG_3338_neighbor1.tif',
    'Juneau_IFSAR_DTM_AKAlbers_EPSG_3338_filled.tif',
    'eCog',
    r'PRA_frequent\info',
    'PRA_frequent',
    'scene.nc',
    'status.txt']

@subcommand([
    argument('dir0', help='Source run dir'),
    argument('dir1', help='Destination run dir')])
def initcopy(args):
    """Runs a single RAMMS avalanche on the local machine, via Docker"""

    dir0 = os.path.abspath(args.dir0)
    dir1 = os.path.abspath(args.dir1)
    ioutil.sync_files(dir0, _init_files, dir1)

# ------------------------------------------------------------------------

@subcommand([argument('ramms', help='RAMMS directory or release file to inspect')])
def ps(args):
    """Provides status of RAMMS avalanches"""
    release_files = rammsutil.get_release_files(args.ramms)
    #print(release_files)

    df = r_ramms.job_statuses(release_files)
    r_ramms.print_job_statuses(df)

@subcommand([
    argument('run_dir', help='Run directory to use'),
    argument('id', type=int, help='ID of avalanche in run_dir to run')])
def run(args):
    """Runs a single RAMMS avalanche on the local machine, via Docker"""

    run_dir = os.path.abspath(args.run_dir)
    parts = run_dir.split(os.sep)
    job_name = '{}_{}_{}'.format(parts[-2], parts[-1], args.id)

    r_ramms.submit_job(run_dir, job_name)

@subcommand([
    argument('ramms', help='RAMMS directory or release file to inspect'),
    argument('ids', type=int, nargs='*', help='ID of avalanche in run_dir to run')])
def submit(args):
    """Runs RAMMS for many avalanches"""

    ids = None if len(args.ids) == 0 else args.ids

    # Separate into numeric-only and non-numerica args in the spec
    release_files = rammsutil.get_release_files(args.ramms)
    r_ramms.submit_jobs(release_files, ids=ids)

@subcommand([
    argument('ramms', help='RAMMS directory or release file to inspect'),
    argument('ids', type=int, nargs='*', help='ID of avalanche in run_dir to run')])
def enlarge(args):
    """Enlarges domain of jobs that overran"""

    ids = None if len(args.ids) == 0 else args.ids

    # Separate into numeric-only and non-numerica args in the spec
    release_files = rammsutil.get_release_files(args.ramms)
    r_ramms.enlarge_domains(release_files, ids=ids)

@subcommand([
    argument('ramms', help='RAMMS directory or release file to inspect'),
    argument('ids', type=int, nargs='*', help='ID of avalanche in run_dir to inspect')])
def info(args):
    ids = None if len(args.ids) == 0 else args.ids
    release_files = rammsutil.get_release_files(args.ramms)
    infos_df = r_ramms.infos(release_files, ids=ids)


#    df = infos_df[infos_df['final_outflow_volume'] == 0.00]
    df = infos_df
#    df = df[df['final_outflow_volume'] == 0]

    print(df)

@subcommand([
    argument('ramms', help='RAMMS directory or release file to inspect'),
    argument('id', type=int, help='ID of avalanche in run_dir to inspect'),
    argument('ext', default='.out.log', help='Extension of filename to  cat')])
def cat(args):
    r_ramms.cat(args.ramms, [args.id], ext=args.ext, out_bytes=sys.stdout.buffer)

# https://stackoverflow.com/questions/51585110/how-to-encode-a-text-stream-into-a-byte-stream-in-python-3
@subcommand([
    argument('ramms', help='RAMMS directory or release file to inspect'),
    argument('id', type=int, help='ID of avalanche in run_dir to inspect'),
    argument('ext', default='.out.log', help='Extension of filename to  cat')])
def less(args):
    stdout0 = sys.stdout
    try:
        less = subprocess.Popen(['less'], stdin=subprocess.PIPE)
        
        #sys.stdout = codecs.getwriter('utf-8')(less.stdin)
        r_ramms.cat(args.ramms, [args.id], ext=args.ext, out_bytes=less.stdin)
        less.communicate()
    finally:
        sys.stdout = stdout0

@subcommand([
    argument('ramms', help='RAMMS directory or release file to inspect'),
    argument('id', type=int, help='ID of avalanche in run_dir to inspect')])
def ls(args):
    for jb,id,info in r_ramms.ls(args.ramms, [args.id]):
        sdt = '{:04d}-{:02d}-{:02d} {:02d}:{:02d}:{:02d}'.format(*info.date_time)
        print(f'{info.file_size: >11,} {sdt:19} {info.filename}')

@subcommand([
    argument('ramms', help='RAMMS directory or release file to inspect'),
])
def spec(args):
    release_files = rammsutil.get_release_files(args.ramms)
    for fname in release_files:
        print(fname)
#        print('---- tiffmap:')
#        jb = rammsutil.parse_release_file(fname)
#        map = r_ramms.tiffmap(jb)
#        for x in map:
#            print('    ',x)




@subcommand([
    argument('ramms', help='RAMMS directory or release file to inspect'),
])
def mosaic(args):
    release_files = rammsutil.get_release_files(args.ramms)
    r_ramms.do_mosaics(release_files)


#        omap_name = os.path.join(oramms_name.scene_dir, 'maps', f'{oramms_name.ramms_name}_maps.zip')
#        if os.path.exists(omap_name):
#            print(f'=========== Exists, not redoing: {omap_name}')
#            continue

#        print(f'=========== Assembling {oramms_name.ramms_dir}')
#        needs_regen = r_ramms.assemble_stage3(oramms_name, release_files)
#        if needs_regen:
#            r_ramms.run_ramms_stage3(oramms_name)
##        print('orrrrrrrrr ', oramms_name.__dict__)


def rclone_relfiles(src, dest, relfiles, tdir):
    # Rclone the files
        listfile = tdir.filename(prefix='relfiles')
        with open(listfile, 'w') as out:
            for file in relfiles:
                out.write(f'{file}\n')

        # Use that in rclone command
        cmd = ['rclone', '-v', 'copy', '--files-from', listfile,
            src, dest]
        print(' '.join(cmd))
        subprocess.run(cmd, check=True)


@subcommand([
    argument('scene', help='Top-Level scene directory to setup through stages 0 and 1.'),
])
def export(args):
    scene_dir = os.path.abspath(os.path.realpath(args.scene))
    scene_args = params.load(scene_dir)

    snowdepth0_leaf = os.path.split(config.roots.syspath(scene_args['snowdepth_file']))[1]
    snowdepth0_root = os.path.splitext(snowdepth0_leaf)[0]
    export_name = f"{scene_args['basename']}_{snowdepth0_root}_{scene_args['downscale']}"


    with ioutil.TmpDir() as tdir:
        # Top-level files
        snowdepth_leaf = f"{snowdepth0_root}_{scene_args['name']}_{scene_args['downscale']}.tif"
        rclone_relfiles(
            os.path.join(config.roots.lookup['PRJ'], scene_args['name']),
            f'alaska:AvalancheShare/results/{export_name}',
            ['scene.nc', 'scene.cdl', snowdepth_leaf], tdir)


        # File ins maps/ directory
        relfiles = list()
        dir = os.path.join(scene_dir, 'maps')
        for name in os.listdir(dir):
            if name.endswith('.zip'):
                relfiles.append(name)

        rclone_relfiles(
            os.path.join(config.roots.lookup['PRJ'], scene_args['name'], 'maps'),
            f'alaska:AvalancheShare/results/{export_name}',
            relfiles, tdir)


@subcommand([
    argument('scene', help='Top-Level scene directory to setup through stages 0 and 1.'),
])
def setup_scene(args):
    scene_dir = args.scene
    scene_args = params.load(scene_dir)
    print(scene_args)

    stages.run_stage0(scene_dir)
    stages.run_stage1(scene_dir)



# ---------------------------------------------------------------------
def get_exp_dir(exp_mod):
    return config.roots.join('PRJ', exp_mod.name)

@subcommand([
    argument('experiment-module',
        help='Python module describing the experiment'),
])
def step1(args):
    """Generate grid defining active domains.  The extent of future
    steps likely depends on this."""

    exp_mod = load_exp_mod(getattr(args, 'experiment-module'))
    exp_dir = get_exp_dir(exp_mod)

    makefile = make.Makefile()
    makefile.add(r_experiment.r_active_domains(exp_mod))
    makefile.generate(os.path.join(exp_dir, 'init_mk'), run=True, ncpu=1)
# -----------------------------------------------------------
experiment_specRE = re.compile(r'([^.]+)\.([^.]+)$')
def _parse_experiment_spec(spec):
    match = experiment_specRE.match(spec)
    return (match.group(1), match.group(2))

@subcommand([
    argument('experiment-spec', type=_parse_experiment_spec,
        help='Python module and combo function describing the experiment, eg: e_alaska.juneau'),
#    argument('-c', '--combos', default='full',
#        help='Name of combo-generating function'),
])
def step2(args):
    """Create required DEMs, Forest files, scene definitions, etc.
    NO Proprietary Software in this step, it can run with high levels of parallelism."""

    sexp_mod, sexp_fn = getattr(args, 'experiment-spec')

    # Load the module (initial 'akramms.' is optional)
    exp_mod = load_exp_mod(sexp_mod)
    exp_dir = get_exp_dir(exp_mod)

    # Load functions from module
    combos_fn = getattr(exp_mod, sexp_fn)     # List the combos
    add_experiment_fn = getattr(exp_mod, 'add_experiment')    # Select out a DEM tile
    #add_combo_fn = getattr(exp_mod, 'add_combo')    # Comobs to rules

    # Generate the makefile
    makefile = make.Makefile()

    # Add the experiment and combos
    add_experiment_fn(makefile, combos_fn())

    makefile.generate(os.path.join(exp_dir, 'init_mk'), run=True, ncpu=config.setup_ncpu)


@subcommand([
    argument('experiment-spec', type=_parse_experiment_spec,
        help='Python module and combo function describing the experiment, eg: e_alaska.juneau'),
])
def step3(args):
    """Go through RAMMS Stage 0 and 1: ArcGIS and eCognition, setting up RAMMS scenes to run.  Then run RAMMS stage 0 and 1 on each scene."""
    import setuptools
    from akramms.util import harnutil


    sexp_mod, sexp_fn = getattr(args, 'experiment-spec')

    # Make sure the domain finder C++ code is compiled. (needed for RAMMS Stage 1)
    setup_py = os.path.join(harnutil.HARNESS, 'akramms', 'setup.py')
    prefix = os.path.join(harnutil.HARNESS, 'akramms', 'inst')
    cmd = ['install', '--prefix', prefix]
    print('setup.py ', cmd)
    setuptools.sandbox.run_setup(setup_py, cmd)


    # Load the module (initial 'akramms.' is optional)
    exp_mod = load_exp_mod(sexp_mod)
    exp_dir = get_exp_dir(exp_mod)

    # Load functions from module
    combos_fn = getattr(exp_mod, sexp_fn)     # List the combos

    # Generate the makefile
    makefile = make.Makefile()
    for combo in combos_fn():
        scene_dir = os.path.join(exp_mod.dir, exp_mod.combo_to_scene_subdir(combo))
        print(f'----- Adding Scene: {scene_dir}')
        stages.add_stage0_rules(makefile, scene_dir)

        # RAMMS Stage 1...
#        ramms_dirs_release_files = add_stage1_rules(makefile, scene_dir)

    makefile.generate(os.path.join(exp_dir, 'init_mk'), run=True, ncpu=1)

# ------------------------------------------------------------------

@subcommand([argument('ramms', help='RAMMS directory or release file to inspect')])
def ramms(args):
    """Run RAMMS Stage 1 and prerequisites on (possibly) a single release file.  Used for debugging."""
    release_files = rammsutil.get_release_files(args.ramms)
    #print(release_files)

    makefile = make.Makefile()

    for release_file in release_files:
        jb = rammsutil.parse_release_file(release_file)
        scene_dir = jb.scene_dir    # Use this at end
        scene_args = params.load(jb.scene_dir)

        dem_file = scene_args['dem_file']
        dem_filled_file = os.path.splitext(dem_file)[0] + '_filled.tif'

        # Different directory for chull and domain
        chull_file = os.path.join(jb.ramms_dir, 'CHULL', '{}_chull.shp'.format(jb.ramms_name))
        domain_file = os.path.join(jb.ramms_dir, 'DOMAIN', '{}_dom.shp'.format(jb.ramms_name))
        makefile.add(r_domain_builder.domain_rule(
            dem_filled_file, release_file, chull_file, domain_file, min_alpha=18., margin=config.initial_margins[jb.pra_size]))


        # RAMMS Stage 1: IDL Prep
        stage1_outputs = makefile.add(r_ramms.ramms_stage1_rule(
            release_file, dem_file, [release_file, dem_file, domain_file], dry_run=False, submit=config.auto_submit)).outputs

    makefile.generate(os.path.join(scene_dir, 'ramms_mk'), run=True, ncpu=1)

# ------------------------------------------------------------------
@subcommand([
    argument('scene', help='Top-Level scene directory to setup through stages 0 and 1.'),
])
def step4(args):
    """Run RAMMS Stage 1 and submit avalanches to HTCondor."""
    scene_dir = args.scene
    scene_args = params.load(scene_dir)
    print(scene_args)

    stages.run_stage0(scene_dir)
    stages.run_stage1(scene_dir)

@subcommand([
    argument('avals', nargs='*', help='Items to feed to avalanche spec parser'),
])
def parse(args):
    aspecs, nc_fnames = avalparse.parse_aval_specs(args.avals)
    print('============ AvalTuple Specs')
    for aspec in aspecs:
        print(aspec)
    print('============ nc_fnames')
    for ncf in nc_fnames:
        print(ncf)


@subcommand([
    argument('avals', nargs='*', help='Items to feed to avalanche spec parser'),
])
def archive(args):
    from akramms import archive
    aspecs, nc_fnames = avalparse.parse_aval_specs(args.avals)
    for aspec in aspecs:
        print(aspec)
        archive.archive_combo(aspec.exp_mod, aspec.combo, aspec.ids, ok_statuses={archive.OK})

def main():
    args = cli.parse_args()
    if args.subcommand is None:
        cli.print_help()
    else:
        args.func(args)

main()
