#!/usr/bin/env python
#

#import cProfile
import netCDF4
import pandas as pd
from akramms import config,params
import akramms.parse
import argparse,itertools,os,subprocess,sys,io,codecs,re,pickle
from akramms import r_experiment,stages
from akramms.util import rammsutil,exputil
from uafgi.util import ioutil,make
import importlib
from akramms import r_domain_builder, r_ramms, resolve
# ------------------------------------------------------------------------
# https://mike.depalatis.net/blog/simplifying-argparse.html
# https://gist.github.com/mivade/384c2c41c3a29c637cb6c603d4197f9f

cli = argparse.ArgumentParser()
subparsers = cli.add_subparsers(dest="subcommand")

def argument(*name_or_flags, **kwargs):
    """Convenience function to properly format arguments to pass to the
    subcommand decorator.
    """
    return (list(name_or_flags), kwargs)

def subcommand(args=[], parent=subparsers):
    def decorator(func):
#        if command == '':
#            command = func.__name__
        name = func.__name__
        parser = parent.add_parser(name, description=func.__doc__)
        for arg in args:
            parser.add_argument(*arg[0], **arg[1])
        parser.set_defaults(func=func)
    return decorator
# ------------------------------------------------------------------------
def run_setup_py():
    import setuptools.sandbox
    from akramms.util import harnutil

    setup_py = os.path.join(harnutil.HARNESS, 'akramms', 'setup.py')
    prefix = os.path.join(harnutil.HARNESS, 'akramms', 'inst')
    cmd = ['install', '--prefix', prefix]
    print('setup.py ', cmd)
    setuptools.sandbox.run_setup(setup_py, cmd)
# ------------------------------------------------------------------------
# Files and folders to copy from one scene to jumpstart the next.
# TODO: Make this work for general scenes
_init_files = [
    'stats_kernel.txt',
    'crs.prj',
    'data_prep_PRA_args.pik',
    'juneau1_DataPrep_InputParameters.csv',
    'Juneau_IFSAR_DTM_AKAlbers_EPSG_3338_sinks.tif',
    'Juneau_IFSAR_DTM_AKAlbers_EPSG_3338_neighbor1.tif',
    'Juneau_IFSAR_DTM_AKAlbers_EPSG_3338_filled.tif',
    'eCog',
    r'PRA_frequent\info',
    'PRA_frequent',
    'scene.nc',
    'status.txt']

@subcommand([
    argument('dir0', help='Source run dir'),
    argument('dir1', help='Destination run dir')])
def initcopy(args):
    """Runs a single RAMMS avalanche on the local machine, via Docker"""

    dir0 = os.path.abspath(args.dir0)
    dir1 = os.path.abspath(args.dir1)
    ioutil.sync_files(dir0, _init_files, dir1)

# ------------------------------------------------------------------------

@subcommand([argument('ramms', help='RAMMS directory or release file to inspect')])
def ps(args):
    """Provides status of RAMMS avalanches"""
    release_files = rammsutil.get_release_files(args.ramms)
    #print(release_files)

    df = r_ramms.job_statuses(release_files)
    r_ramms.print_job_statuses(df)

@subcommand([
    argument('run_dir', help='Run directory to use'),
    argument('id', type=int, help='ID of avalanche in run_dir to run')])
def run(args):
    """Runs a single RAMMS avalanche on the local machine, via Docker"""

    run_dir = os.path.abspath(args.run_dir)
    parts = run_dir.split(os.sep)
    job_name = '{}_{}_{}'.format(parts[-2], parts[-1], args.id)

    r_ramms.submit_job(run_dir, job_name)

@subcommand([
    argument('ramms', help='RAMMS directory or release file to inspect'),
    argument('ids', type=int, nargs='*', help='ID of avalanche in run_dir to run')])
def submit(args):
    """Runs RAMMS for many avalanches"""

    ids = None if len(args.ids) == 0 else args.ids

    # Separate into numeric-only and non-numerica args in the spec
    release_files = rammsutil.get_release_files(args.ramms)
    r_ramms.submit_jobs(release_files, ids=ids)

_chunktypeRE = re.compile('CHUNKS(\d+)?')
@subcommand([
    argument('query', nargs='*', help='Avalanche query, resolved to ID level'),
])
def enlarge(args):

    # Obtain df of relevant Avalanche IDs in original chunks
    parseds = akramms.parse.parse_args(args.query)
    akdf0 = resolve.resolve_to(
        parseds, args.level, level='combo', scenetypes={'x'}, realized=True)

    # Separate by experiment (usually only one)
    for exp,akdf1 in akdf0.groupby('exp'):
        expmod = parse.load_expmod(exp)

        # Separate by combo (AKRAMMS scene)
        for combo,akdf2 in akdf1.groupby('combo'):
            scenedir = expmod.combo_to_scenedir(combo)

            # Determine most recent chunktype, and the one we will write to
            # (TODO: Reuse this code somewhere)
            max_id = -1
            for name in os.listdir(scenedir)
                match = _chunktypeRE.match(name)
                if match is not None:
                    sid = matc.group(1)
                    id = 0 if sid is None else int(sid)
                    max_id = max(max_id, id)
            last_chunktype = 'CHUNKS' if max_id==0 else f'CHUNKS{max_id}'
            next_chunktype = f'CHUNKS{max_id+1}'

            # Generate Avalanche IDs
            akdf3 = resolve.resolve_releasefile(
                akdf2, scenetypes={'x'}, chunktypes={last_chunktype})
            akdf3 = resolve.resolve_id(akdf3, realized=True).set_index('id')

            # Add a 'jobstatus' and 'jbkey' columns to the dataframe
            akdf3 = jobolib.add_job_status(scenedir, akdf3)



    query_fname = args.query[0]

    # Read release dataframe from ALL size classes
    with open(query_fname, 'rb') as fin:
        scene_dir = pickle.load(fin)
        release_df = pickle.load(fin)

    r_ramms.enlarge_domains(scene_dir, release_df)


@subcommand([
    argument('ramms', help='RAMMS directory or release file to inspect'),
    argument('ids', type=int, nargs='*', help='ID of avalanche in run_dir to inspect')])
def info(args):
    ids = None if len(args.ids) == 0 else args.ids
    release_files = rammsutil.get_release_files(args.ramms)
    infos_df = r_ramms.infos(release_files, ids=ids)
    df = infos_df
    print(df)

@subcommand([
    argument('ramms', help='RAMMS directory or release file to inspect'),
    argument('id', type=int, help='ID of avalanche in run_dir to inspect'),
    argument('ext', default='.out.log', help='Extension of filename to  cat')])
def cat(args):
    r_ramms.cat(args.ramms, [args.id], ext=args.ext, out_bytes=sys.stdout.buffer)

# https://stackoverflow.com/questions/51585110/how-to-encode-a-text-stream-into-a-byte-stream-in-python-3
@subcommand([
    argument('ramms', help='RAMMS directory or release file to inspect'),
    argument('id', type=int, help='ID of avalanche in run_dir to inspect'),
    argument('ext', default='.out.log', help='Extension of filename to  cat')])
def less(args):
    stdout0 = sys.stdout
    try:
        less = subprocess.Popen(['less'], stdin=subprocess.PIPE)
        
        #sys.stdout = codecs.getwriter('utf-8')(less.stdin)
        r_ramms.cat(args.ramms, [args.id], ext=args.ext, out_bytes=less.stdin)
        less.communicate()
    finally:
        sys.stdout = stdout0

@subcommand([
    argument('ramms', help='RAMMS directory or release file to inspect'),
    argument('id', type=int, help='ID of avalanche in run_dir to inspect')])
def ls(args):
    for jb,id,info in r_ramms.ls(args.ramms, [args.id]):
        sdt = '{:04d}-{:02d}-{:02d} {:02d}:{:02d}:{:02d}'.format(*info.date_time)
        print(f'{info.file_size: >11,} {sdt:19} {info.filename}')

@subcommand([
    argument('ramms', help='RAMMS directory or release file to inspect'),
])
def spec(args):
    release_files = rammsutil.get_release_files(args.ramms)
    for fname in release_files:
        print(fname)
#        print('---- tiffmap:')
#        jb = rammsutil.parse_release_file(fname)
#        map = r_ramms.tiffmap(jb)
#        for x in map:
#            print('    ',x)




def rclone_relfiles(src, dest, relfiles, tdir):
    # Rclone the files
        listfile = tdir.filename(prefix='relfiles')
        with open(listfile, 'w') as out:
            for file in relfiles:
                out.write(f'{file}\n')

        # Use that in rclone command
        cmd = ['rclone', '-v', 'copy', '--files-from', listfile,
            src, dest]
        print(' '.join(cmd))
        subprocess.run(cmd, check=True)


@subcommand([
    argument('scene', help='Top-Level scene directory to setup through stages 0 and 1.'),
])
def export(args):
    scene_dir = os.path.abspath(os.path.realpath(args.scene))
    scene_args = params.load(scene_dir)

    snowdepth0_leaf = os.path.split(config.roots.syspath(scene_args['snowdepth_file']))[1]
    snowdepth0_root = os.path.splitext(snowdepth0_leaf)[0]
    export_name = f"{scene_args['basename']}_{snowdepth0_root}_{scene_args['downscale']}"


    with ioutil.TmpDir() as tdir:
        # Top-level files
        snowdepth_leaf = f"{snowdepth0_root}_{scene_args['name']}_{scene_args['downscale']}.tif"
        rclone_relfiles(
            os.path.join(config.roots.lookup['PRJ'], scene_args['name']),
            f'alaska:AvalancheShare/results/{export_name}',
            ['scene.nc', 'scene.cdl', snowdepth_leaf], tdir)


        # File ins maps/ directory
        relfiles = list()
        dir = os.path.join(scene_dir, 'maps')
        for name in os.listdir(dir):
            if name.endswith('.zip'):
                relfiles.append(name)

        rclone_relfiles(
            os.path.join(config.roots.lookup['PRJ'], scene_args['name'], 'maps'),
            f'alaska:AvalancheShare/results/{export_name}',
            relfiles, tdir)


@subcommand([
    argument('scene', help='Top-Level scene directory to setup through stages 0 and 1.'),
])
def setup_scene(args):
    scene_dir = args.scene
    scene_args = params.load(scene_dir)
    print(scene_args)

    stages.run_stage0(scene_dir)
    stages.run_stage1(scene_dir)



# ---------------------------------------------------------------------
def get_exp_dir(exp_mod):
    return config.roots.join('PRJ', exp_mod.name)

@subcommand([
    argument('experiment-module',
        help='Python module describing the experiment'),
])
def step1(args):
    """Generate grid defining active domains.  The extent of future
    steps likely depends on this."""

    exp_mod = exputil.load(getattr(args, 'experiment-module'))
    exp_dir = get_exp_dir(exp_mod)

    makefile = make.Makefile()
    makefile.add(r_experiment.r_active_domains(exp_mod))
    makefile.generate(os.path.join(exp_dir, 'init_mk'), run=True, ncpu=1)
# -----------------------------------------------------------
def _parse_experiment_spec():    # DUMMY; should this be avalparse.parse_aval_specs??
    pass

# -----------------------------------------------------------
@subcommand([
    argument('experiment-spec', type=_parse_experiment_spec,
        help='Python module and combo function describing the experiment, eg: e_alaska.juneau'),
#    argument('-c', '--combos', default='full',
#        help='Name of combo-generating function'),
])
def step2(args):
    """Create required DEMs, Forest files, scene definitions, etc.
    NO Proprietary Software in this step, it can run with high levels of parallelism."""

    sexp_mod, sexp_fn = getattr(args, 'experiment-spec')

    # Load the module (initial 'akramms.' is optional)
    exp_mod = exputil.load(sexp_mod)
    exp_dir = get_exp_dir(exp_mod)

    # Load functions from module
    combos_fn = getattr(exp_mod, sexp_fn)     # List the combos
    add_experiment_fn = getattr(exp_mod, 'add_experiment')    # Select out a DEM tile
    #add_combo_fn = getattr(exp_mod, 'add_combo')    # Comobs to rules

    # Generate the makefile
    makefile = make.Makefile()

    # Add the experiment and combos
    add_experiment_fn(makefile, combos_fn())

    makefile.generate(os.path.join(exp_dir, 'init_mk'), run=True, ncpu=config.setup_ncpu)


@subcommand([
    argument('experiment-spec', type=_parse_experiment_spec,
        help='Python module and combo function describing the experiment, eg: e_alaska.juneau'),
])
def step3(args):
    """Go through RAMMS Stage 0 and 1: ArcGIS and eCognition, setting up RAMMS scenes to run.  Then run RAMMS stage 0 and 1 on each scene."""
    import setuptools
    from akramms.util import harnutil


    sexp_mod, sexp_fn = getattr(args, 'experiment-spec')

    # Make sure the domain finder C++ code is compiled. (needed for RAMMS Stage 1)
    setup_py = os.path.join(harnutil.HARNESS, 'akramms', 'setup.py')
    prefix = os.path.join(harnutil.HARNESS, 'akramms', 'inst')
    cmd = ['install', '--prefix', prefix]
    print('setup.py ', cmd)
    setuptools.sandbox.run_setup(setup_py, cmd)


    # Load the module (initial 'akramms.' is optional)
    exp_mod = exputil.load(sexp_mod)
    exp_dir = get_exp_dir(exp_mod)

    # Load functions from module
    combos_fn = getattr(exp_mod, sexp_fn)     # List the combos

    # Generate the makefile
    makefile = make.Makefile()
    for combo in combos_fn():
        scene_dir = os.path.join(exp_mod.dir, exp_mod.combo_to_scene_subdir(combo))
        print(f'----- Adding Scene: {scene_dir}')
        stages.add_stage0_rules(makefile, scene_dir)

        # RAMMS Stage 1...
#        ramms_dirs_release_files = add_stage1_rules(makefile, scene_dir)

    makefile.generate(os.path.join(exp_dir, 'init_mk'), run=True, ncpu=1)

# ------------------------------------------------------------------

@subcommand([argument('ramms', help='RAMMS directory or release file to inspect')])
def ramms(args):
    """Run RAMMS Stage 1 and prerequisites on (possibly) a single release file.  Used for debugging."""
    release_files = rammsutil.get_release_files(args.ramms)
    #print(release_files)

    makefile = make.Makefile()

    for release_file in release_files:
        jb = rammsutil.parse_release_file(release_file)
        scene_dir = jb.scene_dir    # Use this at end
        scene_args = params.load(jb.scene_dir)

        dem_file = scene_args['dem_file']
        dem_filled_file = os.path.splitext(dem_file)[0] + '_filled.tif'

        # Different directory for chull and domain
        chull_file = os.path.join(jb.ramms_dir, 'CHULL', '{}_chull.shp'.format(jb.ramms_name))
        domain_file = os.path.join(jb.ramms_dir, 'DOMAIN', '{}_dom.shp'.format(jb.ramms_name))
        makefile.add(r_domain_builder.domain_rule(
            dem_filled_file, release_file, chull_file, domain_file, min_alpha=18., margin=config.initial_margins[jb.pra_size]))


        # RAMMS Stage 1: IDL Prep
        stage1_outputs = makefile.add(r_ramms.ramms_stage1_rule(
            release_file, dem_file, [release_file, dem_file, domain_file], dry_run=False, submit=config.auto_submit)).outputs

    makefile.generate(os.path.join(scene_dir, 'ramms_mk'), run=True, ncpu=1)

# ------------------------------------------------------------------
@subcommand([
    argument('scene', help='Top-Level scene directory to setup through stages 0 and 1.'),
])
def step4(args):
    """Run RAMMS Stage 1 and submit avalanches to HTCondor."""
    scene_dir = args.scene
    scene_args = params.load(scene_dir)
    print(scene_args)

    stages.run_stage0(scene_dir)
    stages.run_stage1(scene_dir)

@subcommand([
    argument('avals', nargs='*', help='Items to feed to avalanche spec parser'),
    argument('-l', '--level', type=str, default='releasefile',
        help='Level of detail to resolve results to: exp|combo|releasefile|id'),
    argument('-s', '--scenetype', nargs='*',
        help='Type of scene to query: x|arc'),
    argument('-r', '--realized', action='store_true',
        help='Base this on the files on disk?'),
])
def parse(args):

    parseds = akramms.parse.parse_args(args.avals)

    kwargs = {'realized': args.realized}
    if args.scenetype is not None:
        kwargs['scenetypes'] = set(args.scenetype)

    akdf = resolve.resolve_to(parseds, args.level, **kwargs)
    print('=========================>>> akdf')
    print(akdf)

    for tup in akdf.itertuples():
        print(tup)
    return


@subcommand([
    argument('avals', nargs='*', help='Items to feed to avalanche spec parser'),
    argument('-f', '--filter', type=str,
        help='Filter to apply, must return True to include, False to exclude.  See avalfilter.py'),
    argument('-o', '--output',
        help='Name of query file to write'),
])
def query(args):
    from akramms import avalquery,avalfilter

    if args.filter is not None:
        filter_in = exputil.parse_filter(args.filter, 'akramms.avalfilter')
    else:
        filter_in = avalfilter.all

    aspecs, nc_fnames0 = avalparse.parse_aval_specs(args.avals)
    aspecs = avalquery.normalize(aspecs)
    nc_fnames, extent = avalquery.query(aspecs, nc_fnames0, filter_in_fn=filter_in)

    # Get exp_mod
    if len(aspecs) > 0:
        sexp_mod = aspecs[0].exp_mod.name
    else:
        # Get exp_mod from the .nc file
        with netCDF4.Dataset(nc_fnames[0]) as nc:
            sexp_mod = nc.variables['provenance'].exp_mod

    # Write query results to file
    if args.output is not None:
        with open(args.output, 'wb') as out:
            # Query results
            pickle.dump(sexp_mod, out)
            pickle.dump(extent, out)
            pickle.dump(nc_fnames, out)

            # Parsed but unprocessed query
            pickle.dump(aspecs, out)
            pickle.dump(nc_fnames0, out)


    print('============ AvalTuple Specs')
    for aspec in aspecs:
        print(aspec)
    print('============ nc_fnames')
    for ncf in nc_fnames:
        print(ncf)


@subcommand([
    argument('avals', nargs='*', help='Items to feed to avalanche spec parser'),
    argument('-f', '--filter', type=str,
        help='Filter to apply, must return True to include, False to exclude.  See avalfilter.py'),
    argument('-o', '--output', required=False, help='Name of query output file to write.'),
])
def rammsquery(args):
    from akramms import rammsfilter,avalquery
    from akramms import rammsquery as rq

    if args.filter is not None:
        filter_in = exputil.parse_filter(args.filter, 'akramms.rammsfilter')
    else:
        filter_in = rammsfilter.all

    aspecs, nc_fnames0 = avalparse.parse_aval_specs(args.avals)
    aspecs = avalquery.normalize(aspecs)

    release_df = rq.query_aspecs(aspecs, filter_in_fn=filter_in)
    print('*********** Query Results:')
    print(release_df)

    scene_dir = aspecs[0].exp_mod.combo_to_scene_dir(aspecs[0].combo)
    print('scene_dir = ', scene_dir)

    # Write query results to file
    if args.output is not None:
        with open(args.output, 'wb') as out:
            # Query results
            pickle.dump(scene_dir, out)
            pickle.dump(release_df, out)

    # Display result
    for id,row in release_df.iterrows():
        print(f'rm {row.out_zip}')


@subcommand([
    argument('query', nargs=1, help='Query file generated via akramms query'),
    #argument('-o', '--output', required=False, help='Name of Mosaic output file to write'),
    argument('--limit', type=int, help='Limit number of avalanches processed (for DEBUGGING)')
])
def mosaic(args):
    run_setup_py()
    from akramms import avalquery,mosaic

    query_fname = args.query[0]
    ofname = os.path.splitext(query_fname)[0] + '.zip'

    # Read the query
    with open(query_fname, 'rb') as fin:
        exp_mod = exputil.load(pickle.load(fin))
        extent = pickle.load(fin)
        nc_fnames = pickle.load(fin)

    if args.limit is not None:
        nc_fnames = nc_fnames[:args.limit]    # DEBUGGING


    ## Do query
    #aspecs0, nc_fnames = avalparse.parse_aval_specs(args.avals)
    #aspecs = avalquery.normalize(aspecs0)
    #nc_fnames, extent = avalquery.query(aspecs, nc_fnames)

    print('query returned ', len(nc_fnames))


    # Do mosaic
    res = exp_mod.resolution
    gridG = exp_mod.gridD.global_grid(res, res)
#    gridM = exp_mod.gridD.sub(113,45, res, res)    # Could be arbitrary rectangle
    gridM = exp_mod.gridD.subgrid(extent[0], extent[1], extent[2], extent[3], res, res)

    with ioutil.TmpDir(tdir='tmp', remove=False) as tdir:
        mosaic.mosaic_avals(gridM, nc_fnames, ofname, tdir)




@subcommand([
    argument('avals', nargs='*', help='Items to feed to avalanche spec parser'),
])
def archive(args):
    from akramms import archive
    aspecs, nc_fnames = avalparse.parse_aval_specs(args.avals)
    for aspec in aspecs:
        print(aspec)
        archive.archive_combo(aspec.exp_mod, aspec.combo, aspec.ids)

def main():
    args = cli.parse_args()
    if args.subcommand is None:
        cli.print_help()
    else:
        args.func(args)

main()
