import functools
import os
from akramms import params

thisdir = os.path.split(os.path.abspath(__file__))[0]

@functools.lru_cache()
def load_tpl(tpl_file):
    """Permanently loads a template from the source directory"""
    with open(os.path.join(thisdir, tpl_file)) as fin:
        return fin.read()
# --------------------------------------------------------------------
_val_scale = {
    'large': 60,
    'medium': 30,
    'small': 20,
    'tiny': 20,
}

# Extra term in a conditional for the 'tiny' step.
_tiny_term_condition = {
    'large': '',
    'medium': '',
    'small': '',
    'tiny': """\t\t\t\t\t\t\t\t\t<TermCondition eCmpr="5" eBaseUnit="0" eJoint="2">
\t\t\t\t\t\t\t\t\t<ProcVrblVal1>
\t\t\t\t\t\t\t\t\t<DValue type="propDscrId">
\t\t\t\t\t\t\t\t\t<PropDscrId GUID="7F30AE70-0DDD-483c-A693-7698C3CB96FF" InstID="Existence of super objects long (1)"></PropDscrId>
\t\t\t\t\t\t\t\t\t</DValue>
\t\t\t\t\t\t\t\t\t</ProcVrblVal1>
\t\t\t\t\t\t\t\t\t<ProcVrblVal2>
\t\t\t\t\t\t\t\t\t<DValue value="1." type="double"></DValue>
\t\t\t\t\t\t\t\t\t</ProcVrblVal2>
\t\t\t\t\t\t\t\t\t</TermCondition>
"""}


def _split_long_polygons(input_layer, step):
    """A section to do one split-long-polygons step.
    input_layer:
        Name of the layer that came before this step.
        Either 'L fine' (if this is the first step)
        or 'L fine long {previous_step}'
    step: 'large', 'medium', 'small' or 'tiny'
        What KIND of step this is.
    """

    tpl = load_tpl('split_long_polygons.tpl')
    output_layer = f'L fine long {step}'
    xml = tpl.format(
        input_layer=input_layer,
        output_layer=output_layer,
        val_scale = _val_scale[step],
        tiny_term_condition = _tiny_term_condition[step])
    return output_layer, xml

# -----------------------------------------------------------------
# How many split_long_polygons steps we run, depending on the return period
_split_long_polygons_steps = {
    10: ['tiny'],
    30: ['small'],
    100: ['medium', 'small'],
    300: ['large', 'medium', 'small']
}

def _split_long_polygonss(return_period):
    """Creates XML for all the split_long_polygons needed for a step, depending on the return period.
    return_period:
        Years of risk of return (eg: 10-year avalanche, 100-year avalanche, etc)
    """
    sections = []
    output_layer = 'L fine'    # output layer of PREVIOUS step
    for step in _split_long_polygons_steps[return_period]:
        output_layer,xml = _split_long_polygons(output_layer, step)
        sections.append(xml)

    return output_layer, ''.join(sections)

map_level_proxy_tpl = \
"""<!-- BEGIN map_level_proxy_tpl step={step} -->
\t\t\t\t<MapLvlProxy strName="L fine long {step}" bVrbl="0">
\t\t\t\t\t<Scope GUID="00000000-0000-0000-0000-000000000000"></Scope>
\t\t\t\t</MapLvlProxy>
<!-- END map_level_proxy_tpl step={step} -->
"""

def _map_level_proxys(return_period):
    return ''.join(map_level_proxy_tpl.format(step=step)
        for step in _split_long_polygons_steps[return_period])
# -----------------------------------------------------------------
# Scale parameter used in the "segmentation2" step
# Keyed by return period
_segmentation2_scale = {10:25, 30:45, 100:60, 300:120}
_min_mean_slope = {10:30, 30:30, 100:28, 300:28}

return_periods = sorted(list(_min_mean_slope.keys()))    # [10,30,100,300]
def return_period_category(return_period):
    return 'frequent' if return_period < 100 else 'extreme'

def get(scene_args, scene_dir, return_period, forest):
    """
    scene_dir:
        Directory of the overall scene (NOT the eCog/ subdir)
        NOTE: This is mounted path from WITHIN the Docker container.
    return_period: [
    """
    tpl = load_tpl('process_tree.tpl')
    slp_output_layer,slp = _split_long_polygonss(return_period)
    return tpl.format(**{
        'LEFT_BRACKET': '{', 'RIGHT_BRACKET': '}',
        'scene_dir': scene_dir,
        'map_level_proxys': _map_level_proxys(return_period),
        'return_period': return_period,
        'return_period_category': return_period_category(return_period),
        '_For': '_For' if forest else '_NoFor',
        'segmentation2_scale': _segmentation2_scale[return_period],
        'split_long_polygonss': slp,
        'split_long_polygonss_output_layer': slp_output_layer,
        'min_mean_slope': _min_mean_slope[return_period],
        'min_pra_elevation': str(scene_args['min_pra_elevation']),
    })
# ------------------------------------------------------------------
def pra_files(scene_args, return_period, forest):
    """Name of PRA file generated by process tree."""
    For = 'For' if forest else 'NoFor'
    rc_cat = return_period_category(return_period)
    pra_file = os.path.join(
        scene_args['scene_dir'],
        f'PRA_{rc_cat}',
        f'PRA_{return_period}y_{For}.shp')

    pra_burn_file = pra_file[:-4] + '_burn.pik.gz'
    return pra_file,pra_burn_file
